services:
  - type: web
    name: pdf-qa-app
    env: python
    region: oregon
    plan: free
    startCommand: "streamlit run AisocRawAndStupid.py"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"